pose_parameters:
  pipe: {t_vec: [[30], [10], [-160]], t_vec_up: [[30], [10], [-280]], r_vec: [[0], [0], [0]]}
  E3u: {t_vec: [[34], [200], [33]], t_vec_up: [[34], [327], [33]], r_vec: [[1.570796326795], [0], [0]]}
  A1: {t_vec: [[37], [37], [324]], t_vec_up: [[37], [37], [324]], r_vec: [[3.14159265359], [0], [0]]}
  
  

